project_name: fury-cli
version: 2

builds:
  - binary: fury
    main: ./cmd/fury
    ldflags: -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

universal_binaries:
  - name_template: fury
    replace: true

archives:
  - format: tar.gz
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{- title .Os }}{{ end }}_
      {{- if eq .Arch "all" }}universal
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  disable: true

release:
  draft: true

nfpms:
  - id: nfpm-default
    package_name: fury-cli

    vendor: Gemfury.com
    homepage: https://fury.co
    maintainer: Gemfury Team <team@gemfury.com>
    description: Gemfury CLI
    license: Proprietary

    formats:
      - deb

    bindir: /usr/bin

publishers:
  - name: gemfury-repo
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F p1=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/cli/
    ids:
      - nfpm-default

brews:
  -
    # Name template of the recipe
    name: fury-cli

    # GitHub repository to receive formula
    repository:
      owner: gemfury
      name: homebrew-tap
      token: "{{ .Env.BREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    commit_author:
      email: goreleaser@gemfury.com
      name: goreleaser

    # Folder inside the repository to put the formula.
    directory: Formula

    # App's homepage.
    homepage: "https://gemfury.com/"

    # App's description.
    description: "CLI For Gemfury Package Repository"

    # Conflicts with Ruby CLI
    conflicts:
      - gemfury

    # Run to `brew test` the formula.
    test: |
      system "#{bin}/fury --version"
