project_name: fury

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: fury
    main: ./cmd/fury
    ldflags: -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{- title .Os }}{{ end -}}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else if eq .Arch "arm" }}ARMv7
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  draft: true

nfpms:
  - id: nfpm-default
    package_name: fury-cli

    vendor: Gemfury.com
    homepage: https://fury.co
    maintainer: Gemfury Team <team@gemfury.com>
    description: Gemfury CLI
    license: Proprietary

    formats:
      - deb

    bindir: /usr/bin

publishers:
  - name: gemfury-repo
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F p1=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/cli/
    ids:
      - nfpm-default

brews:
  -
    # Name template of the recipe
    name: fury-cli

    # GitHub repository to receive formula
    repository:
      owner: gemfury
      name: homebrew-tap
      token: "{{ .Env.BREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    commit_author:
      email: goreleaser@gemfury.com
      name: goreleaser

    # Folder inside the repository to put the formula.
    folder: Formula

    # App's homepage.
    homepage: "https://gemfury.com/"

    # App's description.
    description: "CLI For Gemfury Package Repository"

    # Conflicts with Ruby CLI
    conflicts:
      - gemfury

    # Run to `brew test` the formula.
    test: |
      system "#{bin}/fury --version"
