name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'
    - name: Download modules
      run: go mod download
    - name: Vet
      run: go vet ./...
    - name: Run tests
      run: go test -race -coverprofile coverage.out ./...
    - name: Check code coverage
      run: | # TODO: Raise coverage minimum
        go tool cover -func coverage.out | grep total | \
        awk '{ if (45 <= substr($3, 1, length($3)-1)) { \
          print("Coverage: " $3, "OK"); \
        } else { \
          print("Coverage: " $3, "FAIL"); \
          exit(1) \
        }}'
